### ISSUE TITLE
Misaligned icon for G+

### ISSUE THREAD

**Issue by miclovich** [ImaginariumLTD/zoo-memorial#1]
this is close to the footer.

![screen shot 2014-07-30 at 7 49 08 pm](https://cloud.githubusercontent.com/assets/122275/3752607/e18e9aac-1809-11e4-8869-6b2b04134b75.png)

**Comment by alvinkatojr** [comment]
Which page is that?

**Comment by miclovich** [comment]
Home page (see footer)

**Comment by alvinkatojr** [comment]
![screenshot from 2014-07-30 19 55 05](https://cloud.githubusercontent.com/assets/519988/3752650/4c23f0c4-180a-11e4-998b-15062c263b34.png)

No error here. What browser are you using?

**Comment by miclovich** [comment]
OMG... I'm guessing you'll have to test it on different web browsers.

When I zoom out to about 75% of the screen, it aligns well enough (perhaps responsiveness for wider screens)

This is on Google Chrome on Mac OS X.

**Comment by alvinkatojr** [comment]
Ah yaya. I can only imagine. Talk about a disaster party :( 

More work :(
